/* eslint-disable @next/next/no-img-element */
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.scss'
import { FiChevronLeft, FiChevronRight, FiHome, FiUser, FiVideo, FiPlayCircle, FiPlay, FiCalendar, FiArrowLeft, FiArrowRight, FiFilm, FiYoutube, FiInstagram, FiFacebook } from 'react-icons/fi'
import { FaSpotify } from 'react-icons/fa'
import Divisor2 from '../components/svgs/divisor2.svg'
import Divisor1 from '../components/svgs/divisor1.svg'
import Divisor3 from '../components/svgs/divisor3.svg'
import PibPamLogo from '../components/svgs/pibpamlogo.svg'
import Carousel from '../components/Carousel'
import ProgramCard from '../components/ProgramCard'
import SeriesCard from '../components/SeriesCard'


const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.navBarContainer} >
          <nav className={styles.navBar}>
            <Image src="/pibpam-logo.svg" alt="Vercel Logo" width={196} height={51} />
            <ul>
              <li>
                <Link href="/about">
                  <a>Início</a>
                </Link>
              </li>
              <li>
                <Link href="/about">
                  <a>Sobre</a>
                </Link>
              </li>
              <li>
                <Link href="/about">
                  <a>Programação</a>
                </Link>
              </li>
              <li>
                <Link href="/about">
                  <a>Ministérios</a>
                </Link>
              </li>
              <li>
                <Link href="/about">
                  <a>Mídia</a>
                </Link>
              </li>
            </ul>
          </nav>
        </div>
        <div className={styles.banner} >
          <button className={`${styles.banner_arrow} ${styles.banner_arrow__left}`} >
            <FiChevronLeft />
          </button>
          <div className={styles.backdrop} >
            <div className={styles.banner_content} >
              <h1>Jesus Cristo Vive!</h1>
              <p>
                "Por que vocês estão procurando entre os mortos aquele que vive?<br />
                Ele não está aqui! Ressuscitou!"</p>
              <p>Lucas 24, 5-6</p>
            </div>
          </div>
          <button className={`${styles.banner_arrow} ${styles.banner_arrow__rigth}`} >
            <FiChevronRight />
          </button>
        </div>
        <div className={styles.divisor} >
          <Divisor2 />
          <Divisor1 />
        </div>

        <div className={styles.introduction} >
          <div>
            <div>
              <div>
                <h2>
                  <strong> Bem-Vindo(a) á PIB <br /> Pará de Minas </strong> <br />
                  Um lugar para você e <br /> para sua família.
                </h2>
              </div>
              <div>
                <button><FiHome />Conheça a nossa igreja</button>
                <button><FiUser />Conheça o nosso pastor</button>
                <button><FiPlayCircle />41 Anos de PIBPAM</button>
              </div>
            </div>
            <div>
              Faça-nos uma visita! <br /> Será um prazer receber você!
            </div>
          </div>
        </div>

        <div className={`${styles.divisor} ${styles.divisor__white}`} >
          <Divisor2 />
          <Divisor1 />
        </div>

        <div className={styles.lastTransmission} >
          <div>
            <div>
              <FiVideo />
              <h3>Assista a nossa<br />
                última transmissão</h3>

              <p>
                Celebração da Santa Ceia do Senhor
              </p>

              <p>
                Pr. Alex Oliveira
              </p>
            </div>
            <div>
              <div className={styles.video__backdrop} >
                <FiPlayCircle />
              </div>
            </div>
          </div>
        </div>
        <div className={styles.watchnow} >
          <div>
            <button> <FiPlay /> Assistir Culto On-line</button>
          </div>
        </div>
        <div className={styles.programation} >
          <div>
            <div>
              <FiCalendar />
              <h3> Nossa Programação<br /> da Semana</h3>
              <p> Selecione o evento para mais detalhes.</p>
              <div>
                <button><FiArrowLeft /></button>
                <button><FiArrowRight /></button>
              </div>
            </div>
            <div>
              <Carousel>
                <>
                  <ProgramCard />
                  <ProgramCard />
                  <ProgramCard />
                  <ProgramCard />
                  <ProgramCard />
                </>
              </Carousel>
            </div>
          </div>
        </div>

        <div className={`${styles.divisor} ${styles.divisor__yellow}`} >
          <Divisor2 />
          <Divisor1 />
        </div>

        <div className={styles.series} >
          <div>
            <div>
              <FiFilm />
              <h3>
                Acompanhe nossas séries<br /> de Ministrações.
              </h3>
              <p>
                Nossas série, são sequências de estudos <br /> de determinados assuntos.
              </p>
            </div>
            <div>
              <Carousel>
                <>
                  <SeriesCard />
                  <SeriesCard />
                  <SeriesCard />
                  <SeriesCard />
                </>
              </Carousel>
            </div>
            <div>
              <button><FiArrowLeft /></button>
              <button><FiArrowRight /></button>
            </div>
          </div>
        </div>

        <footer className={styles.footer}>
          <Divisor3 />
          <div className={styles.footerInfo} >
            <div>
              <PibPamLogo />
            </div>
            <div>
              <h4>Contatos</h4>
              <p>Primeira Igreja  Batista em Pará de Minas</p>
              <p>
                Tel: (37) 3232-3070<br />
                Whatsapp: (37) 9 9999-9999
              </p>
              <p>E-mail: emailtal@pibparademinas.com.br</p>
              <p>Av. Presidente Vargas - XXXX<br />
                Providência - Pará de Minas - MG</p>
            </div>
            <div>
              <h4>Acesso Rápido</h4>
              <ul>
                <li>
                  Ministérios
                </li>
                <li>
                  Programação
                </li>
                <li>
                  Cultos
                </li>
                <li>
                  Séries
                </li>
              </ul>
            </div>
            <div>
              <h4>Redes Sociais</h4>
              <ul>
                <li> <FiYoutube /> YouTube</li>
                <li> <FiInstagram /> Instagram</li>
                <li> <FiFacebook /> Facebook</li>
                <li> <FaSpotify /> Spotify</li>
              </ul>
            </div>
          </div>
          <div className={styles.copy}>
            © 2022 - Todos os direitos pertecem a Primeira Igreja Batista em Pará de Minas
          </div>
        </footer>
      </main >
    </div >
  )
}

export default Home
